version: '3'

services:
  postgres:
    container_name: bm-postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bonemetastasis
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgres
    networks: 
      - postgres-network
  api:
    container_name: bm-api
    build: .
    depends_on: 
      - postgres
    networks: 
      - postgres-network
    ports: 
      - 3333:3333
volumes:
  postgres-data:

networks: 
  postgres-network: