version: '3'

services:
  postgres:
    container_name: bm-postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bonemetastasis
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks: 
      - postgres-network
  api:
    container_name: bm-api
    image: bm-api
    environment: 
      - NODE_ENV=development 
      - apiUrl=http://localhost:3333
    build: .
    depends_on: 
      - postgres
    networks: 
      - postgres-network
    ports: 
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/var/apps/bm-server
volumes:
  postgres-data:
networks: 
  postgres-network: