version: '3'

services:
  postgres:
    container_name: bm-postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bonemetastasis
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks: 
      - postgres-network
  api:
    container_name: bm-api
    image: bm-api
		environment: 
		  - NODE_ENV=production 
			- apiUrl=https://api.bm-diag.org
    build: .
    depends_on: 
      - postgres
    networks: 
      - postgres-network
    ports: 
      - 3333:3333
    volumes:
      - uploads-data:/var/apps/bm-server/uploads
volumes:
  postgres-data:
  uploads-data:
networks: 
  postgres-network: