version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bonemetastasis
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgres
volumes:
  postgres-data: